name: CI/CD Pipeline for Python Discord Bot

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  deploy:
    name: Deploy to AWS Lightsail
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/uvic-course-bot:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/uvic-course-bot:latest

    # Deploy the Docker container on AWS Lightsail
    - name: Deploy to AWS Lightsail
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key

        ssh -i ssh_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << EOF
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/uvic-course-bot:latest
        sudo docker stop uvic-course-bot || true
        sudo docker rm uvic-course-bot || true
        sudo docker run -d \
          --name uvic-course-bot \
          --restart always \
          -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}\
          -e GUILD_IDS=${{ secrets.GUILD_IDS }} \
          ${{ secrets.DOCKER_USERNAME }}/uvic-course-bot:latest