name: Deploy

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/uvic-course-bot:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/uvic-course-bot:latest

    - name: SSH into server and start container
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key

        ssh -i ssh_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << EOF
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/uvic-course-bot:latest
        sudo docker stop uvic-course-bot || true
        sudo docker rm uvic-course-bot || true
        sudo docker run --env-file /home/ubuntu/uvic-course-bot/.env -d \
          --name uvic-course-bot \
          --restart always \
          ${{ secrets.DOCKER_USERNAME }}/uvic-course-bot:latest